### ISSUE TITLE
Seeking Comments on Draft Governance Document

### ISSUE THREAD

**Issue by rabernat** [pangeo-data/governance#10]
We have merged the initial commits to our governance document (#1, #2, #3, #4, #5, #6, #7), but we have not yet adopted it. It is just a draft.
https://github.com/pangeo-data/governance/blob/master/governance_DRAFT.md
__Now we are seeking comments and feedback from the community.__
Anyone and everyone is welcome and encouraged to provide their input

Note that this initial draft is largely based on Project Jupyter's governance repo: https://github.com/jupyter/governance
Because Pangeo and Jupyter are very different projects, some of that language might not be appropriate for our community.

The comment period will remain open for at least two weeks (until 5 September 2018).

To provide feedback on the draft, please _[open a new issue](https://github.com/pangeo-data/governance/issues/new)_, and refer back to this issue.

**Comment by jhamman** [comment]
So we've blown past September 5th (mentioned here) and October 9 (mentioned [here](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/pangeo/Oj0Ki_M-LU8)). I suggest we bring the initial draft stage to a close. Based on @rabernat's proposal ([here](https://github.com/pangeo-data/governance/issues/8)), he and @kmpaul have some work to do to finalize things. 

There will always be more work to do on these issues but that shouldn't keep us from moving forward in finalizing version zero.

**Comment by rabernat** [comment]
closed by #21
