### ISSUE TITLE
Clarification on Project Contributors

### ISSUE THREAD

**Issue by kmpaul** [pangeo-data/governance#14]
In "The Project" section, Contributors are defined fairly narrowly in terms of GitHub contributions and a vague "other work" reference.

However, in the "Council Membership" section, Contributors that are said to be eligible for Council Membership are defined more broadly, with explicit mention that GitHub contributions are not the only way of contributing to The Project.  

I like the definition of Contributors in the "Council Membership" section better.  I feel like we should amend the definition of Contributors in "The Project" section to match.

Thoughts?

**Comment by kmpaul** [comment]
Oh, and this is in reference to #10.

**Comment by mcgibbon** [comment]
I agree in preferring the broader definition.

**Comment by jhamman** [comment]
Can we enumerate possible contributions other than github contributions?

**Comment by kmpaul** [comment]
@jhamman Sorry for the late reply...

The second paragraph of the "Council Membership" section says that contributions include, but are not limited to:

> code, code review, infrastructure work, mailing list and chat participation, community help/building, education and outreach, design work, etc.

I think, perhaps, the same language would be sufficient...?  Comments?

**Comment by kmpaul** [comment]
Looks resolved.  Closing.
