### ISSUE TITLE
Definition of Community?

### ISSUE THREAD

**Issue by kmpaul** [pangeo-data/governance#15]
In multiple places throughout the governance document, "community" is capitalized, and in other places it is not.  My crude understanding of legal documents (taken entirely from my attorney wife) tells me that all defined terms should be capitalized.  Yet, there is no formal definition for "community."

It's unclear to me whether we:

* not capitalize all uses of "community" in the document, or
* we capitalize all uses of "Community" and then add a definition for it in "The Project" section.

If we were to go with the second option, might I suggest a sentence as simple as:

> The collection of all Contributors to The Project is called The Community.

**Comment by kmpaul** [comment]
This is also in reference to #10.

**Comment by jhamman** [comment]
I think this is a good idea. I would also say the Community includes other stakeholders including Users and Funders.

**Comment by kmpaul** [comment]
Another late reply on my side (sorry)...

So, how do you feel about this language:

> The collection of all Contributors to The Project and stakeholders in The Project, including Users and Funders, is called The Community.

**Comment by kmpaul** [comment]
This looks resolved.  Closing.
