### ISSUE TITLE
Comments from the NCAR Office of Diversity, Equity, and Inclusion

### ISSUE THREAD

**Issue by kmpaul** [pangeo-data/governance#17]
I have received some comments on our Governance documents from Kristen Aponte in the NCAR Office of Diversity, Equity, and Inclusion.  The first comment she makes is:

> I thought that there could be a little more explicit commitment to/ valuing of diversity and inclusion. Specifically with the steering committee make up- there was a statement at the end but I think moving that to earlier in the document could be helpful.

I like this suggestion, but I'm wondering where we can move the statement of commitment to make it more prominent...?  Suggestions?

Kristen's next comment was:

> I wonder if having some way for non-committee members nominate folks for the committee would be possible. Chances are you already don't have a very diverse committee, the people nominated are going to reflect the lack of diversity. It might also be helpful to increasing diversity in the community as a whole if you invite someone to be on the steering committee rather than just inviting to join the community? 

I like this suggestion, too.  Currently, our governance documents state that Steering Council nominations are made by the Steering Council themselves.  Letting the community nominate Steering Council could be one way of ensuring that there is an avenue for greater diversity onto the Council.

Thoughts?

**Comment by kmpaul** [comment]
Related to this, are there any objections to the following two suggestions:

1. Moving `code_of_conduct.md` out of the subfolder and placing it prominently next to the `governance.md` file, and referencing it in the section defining Contributors in the "The Project" section.

2. Changing the sentence in the first paragraph of the "Council Membership" section from:

> Potential Council Members are nominated by existing Council Members and voted upon by the existing Council after asking if the potential Member is interested and willing to serve in that capacity. 

to

> Potential Council Members are nominated by Community Contributors and voted upon by the existing Council, after asking if the potential Member is interested and willing to serve in that capacity.

**Comment by jhamman** [comment]
To the second comment - we are currently in a place where anyone can nominate committee members. I think we are taking the necessary steps to insure diversity on this committee. That said, I don't have any objections to the proposed change.

**Comment by kmpaul** [comment]
Should be resolved by PR #20

**Comment by kmpaul** [comment]
Resolved.  Thanks, @rabernat!
