### ISSUE TITLE
Seeking nominations for Pangeo steering council

### ISSUE THREAD

**Issue by rabernat** [pangeo-data/governance#22]
We are seeking nominations for the Pangeo steering council. We will have seven members.

### Nomination Process

Nominations of potential steering council members can be made by anyone from the community, provided that the nominee meets the liberally defined "Contributor" criteria defined above. Self nomination is not allowed. Nominations will take the form of responses to this issue. The nomination should include:
- Name, institutional affiliation, and job title of the nominee
- A few sentences about why that person would be a good steering council member.

Nominations must be "seconded" by another community member via a like (👍) of the post.

Nominations will remain open until Nov. 1, 2018.

###  Decision Process

We will try to reach a decision by consensus, via discussion here on the issue tracker, amongst the project contributors. There is no vote. We strongly hope and expect to achieve a consensus. If a consensus cannot be reached within two weeks, the interim steering council (myself and @kmpaul) will select the seven steering council members from among the nominees. The process will be concluded by Nov. 15, 2018.

The role of the steering council is described fully in the [governance document](https://github.com/pangeo-data/governance/blob/master/governance.md), from which I quote excerpts here.

### The Steering Council

The Project will have a Steering Council that consists of Project Contributors who have produced contributions that are substantial in quality and quantity, and sustained over at least one year. The overall role of the Council is to ensure, through taking input from the Community, the long-term well-being of The Project, both technically and as a community. As The Project draws its strength from representing the Community, it strives to avoid fragmentation of the Community into separate projects, if possible.

During the everyday Project activities, Council Members participate in all discussions, code review and other Project activities as peers with all other Contributors and the Community. In these everyday activities, Council Members do not have any special power or privilege through their membership on the Council. However, it is expected that because of the quality and quantity of their contributions and their expert knowledge of The Project Software and Services that Council Members will provide useful guidance, both technical and in terms of Project direction, to potentially less experienced Contributors.

The Steering Council and its Members play a special role in certain situations. In particular, the Council may:
* Make decisions about the overall scope, vision and direction of The Project.
* Make decisions about strategic collaborations with other organizations or  individuals.
* Make decisions about specific technical issues, features, bugs and pull  requests. They are the primary mechanism of guiding the code review process and  merging pull requests.
* Make decisions about the Services that are run by The Project and manage those Services for the benefit of The Project and Community.
* Make decisions when regular Community discussion doesn’t produce consensus on an issue in a reasonable time frame.

### Council Membership

To become eligible for being a Steering Council Member an individual must be a Project Contributor who has produced contributions that are substantial in quality and quantity, and sustained over at least six months. ~Potential Council Members are nominated by Community Contributors and voted upon by the existing Council, after asking if the potential Member is interested and willing to serve in that capacity.  The Council will be initially formed from the set of existing most active Project Contributors as of August, 2018.~ _[That does not apply here, as we are introducing a new, ad-hoc process to populate the initial steering council.]_

When considering potential Members, the Council will look at candidates with a comprehensive view of their contributions. This will include but is not limited to code, code review, infrastructure work, mailing list and chat participation, community help/building, education and outreach, design work, etc. We are
deliberately not setting arbitrary quantitative metrics (like “100 commits in this repo”) to avoid encouraging behavior that plays to the metrics rather than The Project’s overall well-being. We want to encourage a diverse array of backgrounds, viewpoints and talents in our team, which is why we explicitly do not define code as the sole metric on which Council Membership will be evaluated.

### Definition of Contributors

The Project is developed by a team of distributed developers, called Contributors. Contributors are individuals who have contributed to code, code reviews, documentation, design, and infrastructure, or to mailing lists, chats, community help and community building, education and outreach, or other work in relation to one or more Project repositories. Anyone can be a Contributor. Contributors can be affiliated with any legal entity or none. Contributors participate in The Project by submitting, reviewing and discussing GitHub Pull Requests and Issues and participating in open and public Project discussions on GitHub, Gitter chat rooms and mailing lists. The foundation of Project participation is openness and transparency.

### Diversity

For the purposes of this initial steering council selection, we will interpret the definition of "contributors" as liberally as possible. We seek to increase the diversity of Pangeo, and this includes providing seats for members of underrepresented groups (specifically women and people of color) on the steering council. By increasing diversity in the project leadership, we hope to encourage diversity at all levels. The Pangeo [code of conduct](https://github.com/pangeo-data/governance/blob/master/conduct/code_of_conduct.md) helps ensure that our community is safe and welcoming for people of all backgrounds.

**Comment by kmpaul** [comment]
I will nominate @rabernat.

**Comment by rsignell-usgs** [comment]
I will nominate @jacobtomlinson

**Comment by rabernat** [comment]
Neither of these nominations meets the requirements I outlined in my post. Please update your comments.

**Comment by rsignell-usgs** [comment]
> Contributors are individuals who have contributed to code, code reviews, documentation, design, and infrastructure, or to mailing lists, chats, community help and community building, education and outreach, or other work in relation to one or more Project repositories. Anyone can be a Contributor.

**Comment by rabernat** [comment]
> The nomination should include:
>
> - Name, institutional affiliation, and job title of the nominee
> - A few sentences about why that person would be a good steering council member.

**Comment by rsignell-usgs** [comment]
@rabernat, ah, okay.

**Comment by mcgibbon** [comment]
@rabernat you should consider moving the relevant text from the Nomination Process section to the top, the post is quite long and it took a while for me to find that text (despite thinking I had read the whole post).

**Comment by mcgibbon** [comment]
**Rachel Prudden**, Met Office, Visual Weather Developer
In the years I've known her professionally, Rachel Prudden has been mainly interested in bridging the gap between technology and meteorological science. She puts considerable effort into documentation and communication, as you can see in articles linked from her [Met Office page](http://archived.informaticslab.co.uk/profiles/rachel-prudden.html) (e.g. [this](http://archived.informaticslab.co.uk/technical/infrastructure/2016/03/30/kubernetes-in-pics.html)). She brings expertise in meteorology, machine learning and smartphone application development, which could give insight into approaches towards projects that others without such expertise might not think of.

I think she is well suited to serve the mission statement:

> Our mission is to cultivate an ecosystem in which the next generation of open-source analysis tools for ocean, atmosphere and climate science can be developed, distributed, and sustained. These tools must be scalable in order to meet the current and future challenges of big data, and these solutions should leverage the existing expertise outside of the geoscience community.

**Comment by mcgibbon** [comment]
**Chiara Lepore** (@chiaral), Lamont-Doherty Earth Observatory, Associate Research Scientist
This nomination should be clear from reading [this posting](https://github.com/pangeo-data/governance/issues/8#issuecomment-414892164) by Chiara. It shows many qualities I would like to see on the governing council:

- Chiara prioritizes establishing a friendly and accessible environment for learning and collaboration. This is important to reach more scientists to buy-in to the project. To get wide participation in projects, use of our tools, and feedback from the users of our tools, we need to reach more scientists.
- Chiara pointed out the crux of an issue right now, that the "science" or "non-hacker" part of the project has less visibility on Github. This is just one example of an issue which should be on the radar of the Governing council which Chiara has had the vision to identify and point out. I trust that Chiara would continue to identify and prioritize such issues on the Council.
- When Chiara and Naomi organized and led a Python course, they achieved an attendance of about 50% women. The choices they made gave the highest proportion of women attendees of any Pangeo event I've heard of, and a proportion that is very respectable (for [reference](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5915405/), ~24% of employed environmental scientists and geoscientists are women).
- Her PR to the Code of Conduct shows many leadership qualities I'd like to see in the Council. She [identified](https://github.com/pangeo-data/governance/issues/12#issuecomment-415092430) four great communitites to take notes from. She identified that the document needed to be less verbose to be clear.
- Chiara's [edits](https://github.com/pangeo-data/governance/pull/16/files) to the CoC show a good understanding of how harassment manifests and should be dealt with (which is a responsibility of the Council).
- Generally speaking, Chiara has identified and brought up a number of issues and perspectives that I haven't seen from other vocal community members (including myself), and I think her unique vision is important for the Council.

**Comment by chiaral** [comment]
Nominee: Joe Hamman (@jhamman )
Affiliation: NCAR

Joe has contributed the most to the project in terms of actual code and PRs, and has also lead the development of some critical new functionalities (i.e. Binder) within Pangeo. 
He knows the technical side of the platform better than anyone else and his knowledge is key to support the community and identify the feasibility of future steps. 
He was a major contributor to both NASA and NSF proposals, and also believed from the start in making Pangeo more accessible to the community and developed [many tutorials](https://github.com/pangeo-data/pangeo-tutorial-sea-2018) related to both xarray (for which he is one of the core developers), and dask.

**Comment by jhamman** [comment]
Nominee: Amanda Tan (@amanda-tan)
Affiliation: University of Washington eScience

Amanda is the the UW Research Cloud Computing Cloud Technology Lead Developer. Her extensive experience with cloud deployments, particularly with JupyterHub is a great technical resource to the Pangeo community. She was an early adopter of Pangeo, deploying the Pangeo helm chart on AWS in the very early days of the project. Amanda is going to be working with Pangeo directly as the new NASA-Pangeo project. She also has an extensive background (PhD/post-doc) in the geosciences.

**Comment by rabernat** [comment]
Nominee: Rich Signell (@rsignell-usgs), USGS

Rich was an early adopter and proponent of pangeo. Through his work at ESIP and USGS, he has helped share our efforts with a broad audience. He also led the initial deployments of Pangeo on AWS. While Rich has always positioned himself as an outsider, it is evident to me that has has become an integral part of the collaboration and a valuable member of the team.

**Comment by jacobtomlinson** [comment]
**Nominee**: Kevin Paul (@kmpaul )
**Affiliation**: NCAR

Kevin has been intimately involved in the development of new Python-based technologies at NCAR. He was key in bringing the Pangeo community for the 2018 developers meeting hosted at NCAR. Kevin is also the PI for the NSF program Earth Cube which was designed to develop cyberinfrastructure to meet the current and future requirements of geoscientists.

**Comment by jhamman** [comment]
A reminder to everyone that this process is set to conclude tomorrow.

**Comment by rabernat** [comment]
Thanks for the reminder Joe! The following people have been nominated:
1. @rabernat 
1. @niallrobinson 
1. @RPrudden 
1. @chiaral
1. @jhamman  
1. @amanda-tan 
1. @jacobtomlinson 
1. @rsignell-usgs 
1. @kmpaul 

...and all were seconded

There were two more nominations than there are spots on the council (7). An easy place to start is with the question: _does everyone who was nominated actually want to be on the council?_ If you were nominated but you don't actually want to serve, please say so.

If this doesn't work, we can begin the discussion of how to whittle down the list.

**Comment by rabernat** [comment]
> On a more serious note and because I am completely out of the loop, is there a reason there needs be 7 instead of 9?

No, this was somewhat arbitrary. Maybe we just keep 9? That would be the easiest option for sure! 😄

**Comment by kmpaul** [comment]
I’m sorry for being quiet for a while. I’m on paternity leave, but I wanted to chime in here, briefly, before disappearing again to care for my wife and new little girl. 

We have seconds for all 9 people, but have all of the nominees accepted their nomination?  Considering the “significant contributions” requirement, I might feel like @jhamman better represents Pangeo from the NCAR side of things. So, I’d be willing to step down.

**Comment by kmpaul** [comment]
Agreed. If anyone takes themselves out of consideration, and we have an even number left, take me out to get to an odd number, again.

**Comment by jacobtomlinson** [comment]
I would also be happy to step down in favor of @niallrobinson (who is also on paternity leave) as he can provide more strategic insight from the Met Office viewpoint. 

I'm probably more suited to the potential future technical sub-group anyway :).

**Comment by rabernat** [comment]
Ok, we are slightly past the deadline. Here is what I propose. Both @kmpaul and @jacobtomlinson have indicated that they are willing to step back. I would slightly favor the smaller council, because then we will have a better gender balance. UK Met office also already has two other reps on the council (@niallrobinson and @RPrudden).

So I am proposing that the following council. 

- @rabernat
- @niallrobinson
- @RPrudden
- @chiaral
- @jhamman
- @amanda-tan
- @rsignell-usgs

Would it be fair to say we have a consensus on this?

There will be ample opportunities to evolve this in the council makeup in the future.

**Comment by kmpaul** [comment]
Personally, I think this is an excellent starting council.  If everyone on this list is willing to give @rabernat's comment above a thumbs up, and we have no objections, then I think we have our first council.
