### ISSUE TITLE
Merge initial documents?

### ISSUE THREAD

**Issue by jhamman** [pangeo-data/governance#9]
Might I suggest we merge the existing PRs (#1, #2, #3, #4, #5, #6, and #7) and announce a formal period of comment. Currently, the governance and code of conduct documents are difficult to read in their entirety as they are spread between 7 pull requests. I am not suggesting we rubber-stamp these as final, but rather that we pull them together to help folks view the documents in their composite draft form.

**Comment by rabernat** [comment]
👍 but let's make it very clear that they are DRAFTS.

**Comment by jhamman** [comment]
Anyone else have objections here?

**Comment by rabernat** [comment]
Specifically, after merge, let's rename the document `governance_DRAFT.md`.

**Comment by niallrobinson** [comment]
yes please! I've personally found it easier to use google docs in the past I think - github's felt a bit cumbersome I think
